

# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
from time import sleep
import RPi.GPIO as GPIO
from eserial import *

baudios(9600)

# Main function
def main () :
# Infinite loop
 while True :
  mm = recibir(False)
  printsln(mm)

# Command line execution
if __name__ == '__main__' :
 main()


