# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
from time import sleep
from eserial import *
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM) #puede cambiar a BOARD
led1 = 4  #si cambiar de BCM a Board defina el número del pin acorde a los pines de la raspberry
led2 = 5 #si cambiar de BCM a Board defina el número del pin acorde a los pines de la raspberry

GPIO.setup(led1, GPIO.OUT)
GPIO.setup(led2, GPIO.OUT)

baudios(9600)

# Main function
def main () :
# Infinite loop
 while True :
  prints("Recibiendo datos..  ")
  mensaje = recibir()
  vals = mensaje.split(',')
  k1 = 0
  k2 = 0
  try:
   for i in range(len(vals)):
    k1 += int(vals[i])
   for j in vals:
    k2 += int(j)
  except:
   print("error")
   pass
  sleep(0.2)
  print(k1)
  print(k2)
  printsln("ok")
# Command line execution
if __name__ == '__main__' :
 main()
